### ISSUE TITLE
[FEATURE] Download delområder data

### ISSUE THREAD

**Issue by alfredbirk** [alfredbirk/SmartCity#31]

**Comment by mariusaarsnes** [comment]
Have the borders. but they are simple lines, not polygons which actually mark a whole section. 
Also missing names of the sections.

I have asked Vegard if Mobility Analytics can give us some data

**Comment by mariusaarsnes** [comment]
Doesn't seem like they have data on delområder. Vegard and I will schedule a meeting with them
