### ISSUE TITLE
[BUGFIX] Triple clicking a basic statistical unit does not work

### ISSUE THREAD

**Issue by mariusaarsnes** [alfredbirk/SmartCity#84]
#### When clicking on a basic statistical unit you are zoomed closer to it. If you click it again you are zoomed out. However, if you click the same unit a third time (without clicking on any other) it does not work anymore. 

I am assuming somehting with the state is not updated correctly.

**Comment by emilps** [comment]
This may be fixed when we remove the possibility to click on the map to zoom out
